/*
--1: Regresa el sueldo promedio de los asesores y los agrupa por empresa
SELECT EMPRESA.NOMBRE,
AVG(SUELDO) AS PROMEDIO
FROM ASESOR
JOIN EMPRESA
ON (ASESOR.IDEMPRESA = EMPRESA.IDEMPRESA)
GROUP BY ASESOR.IDEMPRESA,
EMPRESA.NOMBRE;
/
--2: Regresa los DUEÑOS que cumplen años el mismo dia y mes (De cualquier año) en el que un asesor ingreso a trabajar para cualquier empresa
SELECT DUEÑO.NOMBRE AS DUEÑO,
DUEÑO.FNACIMIENTO AS NACIMIENTODUEÑO,
ASESOR.FINGRESO   AS ASESORINGRESO,
ASESOR.NOMBRE     AS ASESOR
FROM DUEÑO
CROSS JOIN ASESOR
WHERE EXTRACT(DAY FROM DUEÑO.FNACIMIENTO) = EXTRACT(DAY FROM ASESOR.FINGRESO)
AND EXTRACT(MONTH FROM DUEÑO.FNACIMIENTO) = EXTRACT(MONTH FROM ASESOR.FINGRESO);
/
--3: Regresa el numero de hospitales que tiene cada colonia
SELECT COLONIA.IDCOLONIA,
COLONIA.NOMBRE,
COUNT(HOSPITALES_CERCANOS.IDCOLONIA)
FROM COLONIA
JOIN HOSPITALES_CERCANOS
ON (COLONIA.IDCOLONIA = HOSPITALES_CERCANOS.IDCOLONIA)
GROUP BY COLONIA.NOMBRE, COLONIA.IDCOLONIA
ORDER BY 3 DESC;
/
--4: Regresa la colonia que tiene más recreativos
SELECT COLONIA.IDCOLONIA,
COLONIA.NOMBRE,
COUNT(RECREATIVOS_CERCANOS.IDCOLONIA)
FROM COLONIA
JOIN RECREATIVOS_CERCANOS
ON (COLONIA.IDCOLONIA = RECREATIVOS_CERCANOS.IDCOLONIA)
GROUP BY COLONIA.NOMBRE, COLONIA.IDCOLONIA
ORDER BY 3 DESC
FETCH FIRST 1 ROWS ONLY;
/
--5: Regresa la cantidad de CASAS que se constru entre los años 1980 y 2000
SELECT COUNT(NUMREGISTRO)
FROM CASA
WHERE FCONSTRUCCION BETWEEN '01/01/1980' AND '31/12/2000';
--6: Regresa el promedio de baños completos de los departamentos registrados que cuentan con al menos 2 amenidades
SELECT ROUND(AVG(DEPARTAMENTO.NBAÑOSCOMPLETOS)) as PROMEDIOBAÑOS
FROM DEPARTAMENTO
JOIN DEPARTAMENTO_AMENIDAD
ON (DEPARTAMENTO.NUMREGISTRO = DEPARTAMENTO_AMENIDAD.NUMREGISTRO)
HAVING COUNT(DEPARTAMENTO_AMENIDAD.NUMREGISTRO) >= 2;
/
*/