/*
--1: Regresa el sueldo promedio de los asesores y los agrupa por empresa
SELECT EMPRESA.NOMBRE,
AVG(SUELDO) AS PROMEDIO
FROM ASESOR
JOIN EMPRESA
ON (ASESOR.IDEMPRESA = EMPRESA.IDEMPRESA)
GROUP BY ASESOR.IDEMPRESA,
EMPRESA.NOMBRE;
/
--2: Regresa los DUEÑOS que cumplen años el mismo dia y mes (De cualquier año) en el que un asesor ingreso a trabajar para cualquier empresa
SELECT DUEÑO.NOMBRE AS DUEÑO,
DUEÑO.FNACIMIENTO AS NACIMIENTODUEÑO,
ASESOR.FINGRESO   AS ASESORINGRESO,
ASESOR.NOMBRE     AS ASESOR
FROM DUEÑO
CROSS JOIN ASESOR
WHERE EXTRACT(DAY FROM DUEÑO.FNACIMIENTO) = EXTRACT(DAY FROM ASESOR.FINGRESO)
AND EXTRACT(MONTH FROM DUEÑO.FNACIMIENTO) = EXTRACT(MONTH FROM ASESOR.FINGRESO);
/
--3: Regresa el numero de hospitales que tiene cada colonia
SELECT COLONIA.IDCOLONIA,
COLONIA.NOMBRE,
COUNT(HOSPITALES_CERCANOS.IDCOLONIA)
FROM COLONIA
JOIN HOSPITALES_CERCANOS
ON (COLONIA.IDCOLONIA = HOSPITALES_CERCANOS.IDCOLONIA)
GROUP BY COLONIA.NOMBRE, COLONIA.IDCOLONIA
ORDER BY 3 DESC;
/
--4: Regresa la colonia que tiene más recreativos
SELECT COLONIA.IDCOLONIA,
COLONIA.NOMBRE,
COUNT(RECREATIVOS_CERCANOS.IDCOLONIA)
FROM COLONIA
JOIN RECREATIVOS_CERCANOS
ON (COLONIA.IDCOLONIA = RECREATIVOS_CERCANOS.IDCOLONIA)
GROUP BY COLONIA.NOMBRE, COLONIA.IDCOLONIA
ORDER BY 3 DESC
FETCH FIRST 1 ROWS ONLY;
/
--5: Regresa la cantidad de CASAS que se constru entre los años 1980 y 2000
SELECT COUNT(NUMREGISTRO)
FROM CASA
WHERE FCONSTRUCCION BETWEEN '01/01/1980' AND '31/12/2000';
--6: Regresa el promedio de baños completos de los departamentos registrados que cuentan con al menos 2 amenidades
SELECT ROUND(AVG(DEPARTAMENTO.NBAÑOSCOMPLETOS)) as PROMEDIOBAÑOS
FROM DEPARTAMENTO
JOIN DEPARTAMENTO_AMENIDAD
ON (DEPARTAMENTO.NUMREGISTRO = DEPARTAMENTO_AMENIDAD.NUMREGISTRO)
HAVING COUNT(DEPARTAMENTO_AMENIDAD.NUMREGISTRO) >= 2;
/
--7: Regresa una tabla ordenando las casas de más antigua a más reciente
SELECT NUMREGISTRO,
MIN(FCONSTRUCCION) AS FECHA_CONSTRUCCION
FROM CASA
GROUP BY NUMREGISTRO
ORDER BY 2 ASC;
/
--8: Regresa los terrenos que no estan asegurados
SELECT *
FROM TERRENO OUTER
LEFT JOIN TERRENO_SEGURO
ON(TERRENO_SEGURO.NUMREGISTRO = OUTER.NUMREGISTRO) WHERE TERRENO_SEGURO.NUMPOLIZA IS NULL;
/
--9: Regresa todas las casas que se encuentran en OAXACA o Puebla y que su colonia se llame Acatlán
SELECT *
FROM CASA
JOIN CASA_DIRECCION
ON(CASA.NUMREGISTRO = CASA_DIRECCION.NUMREGISTRO)
JOIN DIRECCION
ON (CASA_DIRECCION.IDDIRECCION = DIRECCION.IDDIRECCION)
JOIN COLONIA ON(DIRECCION.IDCOLONIA = COLONIA.IDCOLONIA)
WHERE DIRECCION.ESTADO         = 'Oaxaca'
OR DIRECCION.ESTADO            = 'Puebla'
AND COLONIA.NOMBRE = 'Acatlán';
/
--10: Regresa el precio del seguro más caro y el promedio de los seguros
SELECT MAX(PRECIOANUAL) AS PRECIOMAXIMO,
AVG(PRECIOANUAL)      AS PROMEDIO
FROM SEGURO;
/
--11: Regresa el numero de asesores por empresa
SELECT EMPRESA.NOMBRE,
COUNT(IDASESOR)
FROM ASESOR
JOIN EMPRESA
ON (ASESOR.IDEMPRESA = EMPRESA.IDEMPRESA)
GROUP BY EMPRESA.NOMBRE
ORDER BY 2 DESC;
/
--12: Regresa cuantas casas se agregaron por año desde el 2010 hasta el 2018
SELECT SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2010' AND '31/12/2010'
THEN 1
ELSE 0
END)               AS A_2010,
SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2011' AND '31/12/2011'
THEN 1
ELSE 0
END)               AS A_2011,
SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2012' AND '31/12/2012'
THEN 1
ELSE 0
END)               AS A_2012,
SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2013' AND '31/12/2013'
THEN 1
ELSE 0
END)               AS A_2013,
SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2014' AND '31/12/2014'
THEN 1
ELSE 0
END)               AS A_2014,
SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2015' AND '31/12/2015'
THEN 1
ELSE 0
END)               AS A_2015,
SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2016' AND '31/12/2016'
THEN 1
ELSE 0
END)               AS A_2016,
SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2017' AND '31/12/2017'
THEN 1
ELSE 0
END)               AS A_2017,
SUM(
CASE
WHEN FCONSTRUCCION BETWEEN '01/01/2018' AND '31/12/2018'
THEN 1
ELSE 0
END)               AS A_2018
FROM CASA;
/
*/
