create or replace TRIGGER VERIFICA_ASESOR_EMAIL
BEFORE INSERT OR UPDATE OF CORREO ON ASESOR_EMAIL
FOR EACH ROW
WHEN(NOT REGEXP_LIKE(NEW.CORREO, '.*[@].*..*'))
BEGIN 
  RAISE_APPLICATION_ERROR (-20001, 'Introduce un email valido, debe llevar un @ y un .');
END;