/*
Se encarga de verificar que se reciban valores numericos
en los campos (ya que use char en vez de number)
NBAÑOSMEDIOS,
NBAÑOSCOMPLETOS,
NESTACIONAMIENTOS,
NHABITACIONES,
NPISOS,
TAMAÑOHABITABLEMETROS,
TAMAÑOTERRENO
*/
CREATE OR REPLACE TRIGGER NUEVA_CASA BEFORE
  INSERT OR
  UPDATE OF NBAÑOSMEDIOS,
    NBAÑOSCOMPLETOS,
    NESTACIONAMIENTOS,
    NHABITACIONES,
    NPISOS,
    TAMAÑOHABITABLEMETROS,
    TAMAÑOTERRENO ON CASA FOR EACH ROW WHEN(NOT REGEXP_LIKE(NEW.NBAÑOSMEDIOS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.NBAÑOSCOMPLETOS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.NESTACIONAMIENTOS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.NHABITACIONES, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.NPISOS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.TAMAÑOHABITABLEMETROS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.TAMAÑOTERRENO, '^[0-9]')) BEGIN RAISE_APPLICATION_ERROR (-20002, 'Solo debes introducir numeros en el telefono!');
END;