/*
Trigger que agrega un exdueño cada que la propiedad cambia de dueño
*/
CREATE OR REPLACE TRIGGER AGREGA_EXDUEÑO_DEPARTAMENTO BEFORE
  UPDATE OF IDDUEÑO ON DEPARTAMENTO_VENTA_DUEÑO FOR EACH ROW DECLARE BEGIN
  INSERT
  INTO DEPARTAMENTO_EXDUEÑO VALUES
    (
      :OLD.IDDUEÑO,
      :OLD.NUMREGISTRO,
      SYSDATE,
      :OLD.FADQUISICION
    );
END;
\