/*
Se encarga de verificar que se reciban valores numericos
en los campos (ya que use char en vez de number)
NBAÑOSMEDIOS,
NBAÑOSCOMPLETOS,
NESTACIONAMIENTOS,
NHABITACIONES,
TAMAÑOHABITABLEMETROS,
TAMAÑOTERRENO,
UBICADOENPISO,
TOTALENEDIFICIO
*/
CREATE OR REPLACE TRIGGER NUEVO_DEPARTAMENTO BEFORE
  INSERT OR
  UPDATE OF NBAÑOSMEDIOS,
    NBAÑOSCOMPLETOS,
    NESTACIONAMIENTOS,
    NHABITACIONES,
    TAMAÑOHABITABLEMETROS,
    TAMAÑOTERRENO,
    UBICADOENPISO,
    TOTALENEDIFICIO ON DEPARTAMENTO FOR EACH ROW WHEN(NOT REGEXP_LIKE(NEW.NBAÑOSMEDIOS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.NBAÑOSCOMPLETOS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.NESTACIONAMIENTOS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.NHABITACIONES, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.TAMAÑOHABITABLEMETROS, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.TAMAÑOTERRENO, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.UBICADOENPISO, '^[0-9]')
  OR NOT REGEXP_LIKE(NEW.TOTALENEDIFICIO, '^[0-9]')) BEGIN RAISE_APPLICATION_ERROR (-20006, 'Debes introducir solo numeros en NBAÑOSMEDIOS,    
NBAÑOSCOMPLETOS,    
NESTACIONAMIENTOS,    
NHABITACIONES,    
NPISOS,    
TAMAÑOHABITABLEMETROS,    
TAMAÑOTERRENO
UBICADOENPISO
TOTALENEDIFICIO!');
END;
\