--CONSULTA 1

SELECT IDMEDICO,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/17' AND '31/12/17'
    THEN 1
    ELSE 0
  END) AS C_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/18' AND '31/12/18'
    THEN 1
    ELSE 0
  END) AS C_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/19' AND '31/12/19'
    THEN 1
    ELSE 0
  END) AS C_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/17' AND '01/04/17'
    THEN 1
    ELSE 0
  END) AS T1_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/17' AND '01/07/17'
    THEN 1
    ELSE 0
  END) AS T2_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/17' AND '01/10/17'
    THEN 1
    ELSE 0
  END) AS T3_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/17' AND '01/1/18'
    THEN 1
    ELSE 0
  END) AS T4_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/18' AND '01/04/18'
    THEN 1
    ELSE 0
  END) AS T1_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/18' AND '01/07/18'
    THEN 1
    ELSE 0
  END) AS T2_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/18' AND '01/10/18'
    THEN 1
    ELSE 0
  END) AS T3_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/18' AND '01/1/19'
    THEN 1
    ELSE 0
  END) AS T4_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/19' AND '01/04/19'
    THEN 1
    ELSE 0
  END) AS T1_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/19' AND '01/07/19'
    THEN 1
    ELSE 0
  END) AS T2_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/19' AND '01/10/19'
    THEN 1
    ELSE 0
  END) AS T3_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/19' AND '01/1/20'
    THEN 1
    ELSE 0
  END)            AS T4_2019,
  COUNT(IDMEDICO) AS TOTAL_CONSULTAS
FROM MEDICO_CONSULTAR_PACIENTE
GROUP BY IDMEDICO;

---------------------------------------------------------------------------------------

--CONSULTA 2

SELECT PACIENTE.IDPACIENTE, NOMBRE, NUM_CONSULTA, FNACIMIENTO, FECHA_CONSULTA 
FROM MEDICO_CONSULTAR_PACIENTE
JOIN PACIENTE
ON(MEDICO_CONSULTAR_PACIENTE.IDPACIENTE                          = PACIENTE.IDPACIENTE)
WHERE EXTRACT(DAY FROM MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA) = EXTRACT(DAY FROM PACIENTE.FNACIMIENTO) AND EXTRACT(MONTH FROM MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA) = EXTRACT(MONTH FROM PACIENTE.FNACIMIENTO);
--------------------------------------------------------------------------------------

--CONSULTA 3

SELECT MEDICO.IDMEDICO,
  MEDICO.NOMBRE,
  COUNT(MEDICO_CONSULTAR_PACIENTE.IDMEDICO) AS TOTAL_CONSULTAS, ESPECIALIDAD.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD
FROM MEDICO_CONSULTAR_PACIENTE
INNER JOIN MEDICO
ON(MEDICO_CONSULTAR_PACIENTE.IDMEDICO = MEDICO.IDMEDICO)
INNER JOIN MEDICO_TENER_ESPECIALIDAD
ON(MEDICO_TENER_ESPECIALIDAD.IDMEDICO = MEDICO_CONSULTAR_PACIENTE.IDMEDICO)
INNER JOIN ESPECIALIDAD ON (MEDICO_TENER_ESPECIALIDAD.IDESPECIALIDAD = ESPECIALIDAD.IDESPECIALIDAD)
GROUP BY MEDICO.IDMEDICO,
  MEDICO_CONSULTAR_PACIENTE.IDMEDICO,
  MEDICO.NOMBRE, NOMBRE_ESPECIALIDAD
ORDER BY COUNT(MEDICO_CONSULTAR_PACIENTE.IDMEDICO) DESC
FETCH FIRST 1 ROWS ONLY;

---------------------------------------------------------------------------------------

