--CONSULTA 1

SELECT IDMEDICO,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/17' AND '31/12/17'
    THEN 1
    ELSE 0
  END) AS C_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/18' AND '31/12/18'
    THEN 1
    ELSE 0
  END) AS C_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/19' AND '31/12/19'
    THEN 1
    ELSE 0
  END) AS C_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/17' AND '01/04/17'
    THEN 1
    ELSE 0
  END) AS T1_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/17' AND '01/07/17'
    THEN 1
    ELSE 0
  END) AS T2_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/17' AND '01/10/17'
    THEN 1
    ELSE 0
  END) AS T3_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/17' AND '01/1/18'
    THEN 1
    ELSE 0
  END) AS T4_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/18' AND '01/04/18'
    THEN 1
    ELSE 0
  END) AS T1_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/18' AND '01/07/18'
    THEN 1
    ELSE 0
  END) AS T2_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/18' AND '01/10/18'
    THEN 1
    ELSE 0
  END) AS T3_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/18' AND '01/1/19'
    THEN 1
    ELSE 0
  END) AS T4_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/19' AND '01/04/19'
    THEN 1
    ELSE 0
  END) AS T1_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/19' AND '01/07/19'
    THEN 1
    ELSE 0
  END) AS T2_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/19' AND '01/10/19'
    THEN 1
    ELSE 0
  END) AS T3_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/19' AND '01/1/20'
    THEN 1
    ELSE 0
  END)            AS T4_2019,
  COUNT(IDMEDICO) AS TOTAL_CONSULTAS
FROM MEDICO_CONSULTAR_PACIENTE
GROUP BY IDMEDICO;

---------------------------------------------------------------------------------------

--CONSULTA b

SELECT PACIENTE.IDPACIENTE, NOMBRE, NUM_CONSULTA, FNACIMIENTO, FECHA_CONSULTA 
FROM MEDICO_CONSULTAR_PACIENTE
JOIN PACIENTE
ON(MEDICO_CONSULTAR_PACIENTE.IDPACIENTE                          = PACIENTE.IDPACIENTE)
WHERE EXTRACT(DAY FROM MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA) = EXTRACT(DAY FROM PACIENTE.FNACIMIENTO) AND EXTRACT(MONTH FROM MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA) = EXTRACT(MONTH FROM PACIENTE.FNACIMIENTO);
--------------------------------------------------------------------------------------

--CONSULTA c

SELECT MEDICO.IDMEDICO,
  MEDICO.NOMBRE,
  COUNT(MEDICO_CONSULTAR_PACIENTE.IDMEDICO) AS TOTAL_CONSULTAS, ESPECIALIDAD.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD
FROM MEDICO_CONSULTAR_PACIENTE
INNER JOIN MEDICO
ON(MEDICO_CONSULTAR_PACIENTE.IDMEDICO = MEDICO.IDMEDICO)
INNER JOIN MEDICO_TENER_ESPECIALIDAD
ON(MEDICO_TENER_ESPECIALIDAD.IDMEDICO = MEDICO_CONSULTAR_PACIENTE.IDMEDICO)
INNER JOIN ESPECIALIDAD ON (MEDICO_TENER_ESPECIALIDAD.IDESPECIALIDAD = ESPECIALIDAD.IDESPECIALIDAD)
GROUP BY MEDICO.IDMEDICO,
  MEDICO_CONSULTAR_PACIENTE.IDMEDICO,
  MEDICO.NOMBRE, NOMBRE_ESPECIALIDAD
ORDER BY COUNT(MEDICO_CONSULTAR_PACIENTE.IDMEDICO) DESC
FETCH FIRST 1 ROWS ONLY;

---------------------------------------------------------------------------------------

--CONSULTA d

SELECT MEDICO_INGRESAR_PACIENTE.IDPACIENTE,
  PACIENTE.NOMBRE,
  PACIENTE.APATERNO,
  PACIENTE.AMATERNO,
  PACIENTE.FNACIMIENTO,
  MEDICO_INGRESAR_PACIENTE.FECHA_INGRESO
FROM MEDICO_INGRESAR_PACIENTE
JOIN PACIENTE
ON (MEDICO_INGRESAR_PACIENTE.IDPACIENTE = PACIENTE.IDPACIENTE)
WHERE FECHA_INGRESO BETWEEN '01/09/17' AND '31/12/17';

---------------------------------------------------------------------------------------

--CONSULTA e

---------------------------------------------------------------------------------------

--CONSULTA f

SELECT *
FROM PACIENTE
WHERE NOT EXISTS
  (SELECT IDPACIENTE
  FROM MEDICO_CONSULTAR_PACIENTE
  WHERE PACIENTE.IDPACIENTE = MEDICO_CONSULTAR_PACIENTE.IDPACIENTE
  );
---------------------------------------------------------------------------------------

--CONSULTA g

---------------------------------------------------------------------------------------

--CONSULTA H

PREGUNTAR SI QUIERE QUE AGREGUEMOS UN CAMPO ESTADO O SI LO PODEMOS HACER CON CIUDAD

SELECT PACIENTE.IDPACIENTE,
  PACIENTE.NOMBRE,
  PACIENTE.APATERNO,
  PACIENTE.AMATERNO,
  PACIENTE.CALLE,
  PACIENTE.NUMERO,
  PACIENTE.CIUDAD,
  PACIENTE.CP,
  PACIENTE.FNACIMIENTO,
  MEDICO_INGRESAR_PACIENTE.NUM_INGRESO,
  MEDICO_INGRESAR_PACIENTE.HABITACION,
  MEDICO_INGRESAR_PACIENTE.CAMA,
  MEDICO_INGRESAR_PACIENTE.FECHA_INGRESO
FROM PACIENTE
JOIN MEDICO_INGRESAR_PACIENTE
ON (PACIENTE.IDPACIENTE = MEDICO_INGRESAR_PACIENTE.IDPACIENTE)
WHERE PACIENTE.CIUDAD   = 'Paraguay'
AND PACIENTE.APATERNO   = 'Whayman';

-------------------------------------------------------------------------------------

--CONSULTA I

--SELECT COUNT(NUM_CONSULTA) FROM MEDICO_CONSULTAR_PACIENTE;
SELECT SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/17' AND '31/12/17'
    THEN 1
    ELSE 0
  END) AS C_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/18' AND '31/12/18'
    THEN 1
    ELSE 0
  END) AS C_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/19' AND '31/12/19'
    THEN 1
    ELSE 0
  END) AS C_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/17' AND '01/04/17'
    THEN 1
    ELSE 0
  END) AS T1_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/17' AND '01/07/17'
    THEN 1
    ELSE 0
  END) AS T2_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/17' AND '01/10/17'
    THEN 1
    ELSE 0
  END) AS T3_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/17' AND '31/12/17'
    THEN 1
    ELSE 0
  END) AS T4_2017,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/18' AND '01/04/18'
    THEN 1
    ELSE 0
  END) AS T1_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/18' AND '01/07/18'
    THEN 1
    ELSE 0
  END) AS T2_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/18' AND '01/10/18'
    THEN 1
    ELSE 0
  END) AS T3_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/18' AND '31/12/18'
    THEN 1
    ELSE 0
  END) AS T4_2018,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/01/19' AND '01/04/19'
    THEN 1
    ELSE 0
  END) AS T1_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/04/19' AND '01/07/19'
    THEN 1
    ELSE 0
  END) AS T2_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/07/19' AND '01/10/19'
    THEN 1
    ELSE 0
  END) AS T3_2019,
  SUM(
  CASE
    WHEN FECHA_CONSULTA BETWEEN '01/10/19' AND '31/12/19'
    THEN 1
    ELSE 0
  END)                AS T4_2019,
  COUNT(NUM_CONSULTA) AS TOTAL_CONSULTA
FROM MEDICO_CONSULTAR_PACIENTE
ORDER BY COUNT(NUM_CONSULTA)DESC;

FALTA REGRESAR LOS MAS GRANDES--------------------------------
-----------------------------------------------------------------------------------------------------------
--Consulta J

SELECT ESPECIALIDAD.NOMBRE_ESPECIALIDAD AS Especialidad,
  SUM(
  CASE
    WHEN MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA BETWEEN '01/07/17' AND '31/7/17'
    THEN 1
    ELSE 0
  END) AS Julio,
  SUM(
  CASE
    WHEN MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA BETWEEN '01/08/17' AND '31/8/17'
    THEN 1
    ELSE 0
  END) AS Agosto,
  SUM(
  CASE
    WHEN MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA BETWEEN '01/09/17' AND '30/9/17'
    THEN 1
    ELSE 0
  END) AS Septiembre,
  SUM(
  CASE
    WHEN MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA BETWEEN '01/10/17' AND '31/10/17'
    THEN 1
    ELSE 0
  END) AS Octubre,
  SUM(
  CASE
    WHEN MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA BETWEEN '01/07/17' AND '31/7/17'
    THEN 1
    ELSE 0
  END) AS Noviembre,
  SUM(
  CASE
    WHEN MEDICO_CONSULTAR_PACIENTE.FECHA_CONSULTA BETWEEN '01/08/17' AND '31/8/17'
    THEN 1
    ELSE 0
  END) AS Diciembre
FROM MEDICO_CONSULTAR_PACIENTE
JOIN MEDICO_TENER_ESPECIALIDAD
ON (MEDICO_CONSULTAR_PACIENTE.IDMEDICO = MEDICO_TENER_ESPECIALIDAD.IDMEDICO)
JOIN ESPECIALIDAD
ON(MEDICO_TENER_ESPECIALIDAD.IDESPECIALIDAD = ESPECIALIDAD.IDESPECIALIDAD)
GROUP BY ESPECIALIDAD.NOMBRE_ESPECIALIDAD
ORDER BY Especialidad;

-------------------------------------------------------------------------------------

--Consulta K 

SELECT IDPACIENTE,
  (SELECT COUNT(MEDICO.IDMEDICO) FROM MEDICO
  )                                                  AS TOTALMEDICOS,
  COUNT(DISTINCT MEDICO_CONSULTAR_PACIENTE.IDMEDICO) AS TOTALPACIENTE
FROM MEDICO_CONSULTAR_PACIENTE
JOIN MEDICO
ON(MEDICO.IDMEDICO = MEDICO_CONSULTAR_PACIENTE.IDMEDICO)
GROUP BY IDPACIENTE
HAVING COUNT(MEDICO.IDMEDICO) >
  (SELECT COUNT(DISTINCT MEDICO_CONSULTAR_PACIENTE.IDMEDICO)
  FROM MEDICO_CONSULTAR_PACIENTE
  );

  --------------------------------------------------------------------------------

  --Consulta L

  SELECT PACIENTE.IDPACIENTE,
  NOMBRE,
  APATERNO,
  AMATERNO,
  COUNT(MEDICO_INGRESAR_PACIENTE.IDPACIENTE) AS TotalIngresos
FROM MEDICO_INGRESAR_PACIENTE
JOIN PACIENTE
ON(MEDICO_INGRESAR_PACIENTE.IDPACIENTE = PACIENTE.IDPACIENTE)
GROUP BY PACIENTE.IDPACIENTE,
  NOMBRE,
  APATERNO,
  AMATERNO
ORDER BY COUNT(MEDICO_INGRESAR_PACIENTE.IDPACIENTE) DESC
FETCH FIRST 5 ROWS ONLY;


-------------------------------------------------------------------------------------

-- Consulta M

SELECT FECHA_INGRESO
FROM MEDICO_INGRESAR_PACIENTE t1
WHERE NOT EXISTS
  (SELECT *
  FROM MEDICO_INGRESAR_PACIENTE t2
  GROUP BY IDPACIENTE
  HAVING MIN(t2.FECHA_INGRESO) < t1.FECHA_INGRESO
  );

--------------------------------------------------------------------------------------

--CONSULTA N

SELECT t2.IDMEDICO,
  t2.NOMBRE,
  t2.APATERNO,
  t2.AMATERNO,
  t2.CALLE,
  t2.CIUDAD,
  t1.IDSUPERVISOR AS SUPERVISOR,
  t1.CALLE        AS CALLE_SUPERVISOR,
  t2.CIUDAD       AS CIUDAD_SUPERVISOR
FROM MEDICO t1
JOIN MEDICO t2
ON (t1.IDMEDICO = t2.IDSUPERVISOR)
WHERE t1.CALLE  = t2.CALLE
AND t1.CIUDAD   = t2.CIUDAD;


---------------------------------------------------------------------------------------

--CONSULTA O

SELECT ESPECIALIDAD.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD,
  PACIENTE.NOMBRE                       AS NOMBRE,
  PACIENTE.APATERNO                     AS A_PATERNO,
  PACIENTE.AMATERNO                     AS A_MATERNO
FROM MEDICO_INGRESAR_PACIENTE
JOIN PACIENTE
ON (PACIENTE.IDPACIENTE = MEDICO_INGRESAR_PACIENTE.IDPACIENTE)
JOIN MEDICO_TENER_ESPECIALIDAD
ON(MEDICO_INGRESAR_PACIENTE.IDMEDICO = MEDICO_TENER_ESPECIALIDAD.IDMEDICO)
JOIN ESPECIALIDAD
ON (MEDICO_TENER_ESPECIALIDAD.IDESPECIALIDAD = ESPECIALIDAD.IDESPECIALIDAD)
GROUP BY ESPECIALIDAD.NOMBRE_ESPECIALIDAD,
  PACIENTE.NOMBRE,
  PACIENTE.APATERNO,
  PACIENTE.AMATERNO
ORDER BY ESPECIALIDAD.NOMBRE_ESPECIALIDAD;